In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'Col1' : ['A', 'A', 'B', np.nan, 'D', 'C'], 'Col2': [2,1,9,8,7,4], 'Col3':[0,1,9,4,2,3]})

In [3]:
df

  Col1  Col2  Col3
0    A     2     0
1    A     1     1
2    B     9     9
3  NaN     8     4
4    D     7     2
5    C     4     3

In [5]:
df.sort_values(by='Col1')

  Col1  Col2  Col3
0    A     2     0
1    A     1     1
2    B     9     9
5    C     4     3
4    D     7     2
3  NaN     8     4

In [6]:
df.sort_values(by='Col2')

  Col1  Col2  Col3
1    A     1     1
0    A     2     0
5    C     4     3
4    D     7     2
3  NaN     8     4
2    B     9     9

In [9]:
df.sort_values(by=['Col3', 'Col1'], ascending=False)

  Col1  Col2  Col3
2    B     9     9
3  NaN     8     4
5    C     4     3
4    D     7     2
1    A     1     1
0    A     2     0